server {
    listen 80;
    listen [::]:80;
    server_name checkplanilha.anvy.com.br;

    root /var/www/checkplanilha/public;
    index index.php index.html;

    access_log /var/log/nginx/checkplanilha.access.log main;
    error_log /var/log/nginx/checkplanilha.error.log warn;

    client_max_body_size 60M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/run/php-fpm/checkplanilha.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
